
#ifndef REGEXBUILDER_CONFIG_VERSION_HPP
#define REGEXBUILDER_CONFIG_VERSION_HPP

#define REGEXBUILDER_MAJOR @REGEXBUILDER_MAJOR@
#define REGEXBUILDER_MINOR @REGEXBUILDER_MINOR@
#define REGEXBUILDER_PATCH @REGEXBUILDER_PATCH@
#define REGEXBUILDER_RELEASE @REGEXBUILDER_RELEASE@

#endif
